import React from "react";

import CreateContentImage from "./assets/create-content.png";
import EnhanceProductvityImage from "./assets/enhance-productivity.png";
import MoneyImage from "./assets/money.png";
import SaveHoursImage from "./assets/save-hours.png";
import CreativityImage from "./assets/creatitivity.png";
import PlagiarismImage from "./assets/plagiarism.png";
import SimplifyImage from "./assets/simplify.png";
import EditorImg1 from "./assets/editor1.png";
import "./index.css"; // Import the CSS file

const features1 = [
	{
		name: "AI Rewriter that Turns Your AI Text to Undetectable",
		description:
			"You’ll find many AI detection removers out there, but most of them create even more complicated and hard-to-read text that fails to pass AI detection. You don’t have to worry about this with RewriterPro. Our AI Rewriter uses advanced AI technology and natural language processing to transform your AI text into more authentic and strong text in just one click. This helps you bypass AI detectors. ",
	},
	{
		name: "Save Countless Hours.",
		description:
			"ReWriter AI helps you write splendid content    Our AI is programmed to make your sentence rewriting tasks quick and easy.   Suppose you’re a student, teacher, or content creator. In that case, ReWriter AI helps you save tons of time by generating quality and ready-to-publish content within seconds and without compromising the original quality.   All you have to do is paste your basic-written content and click the “Rewrite” button. And by the time you check your phone’s notifications, your final content will be ready.",
	},
	{
		name: "Save Money.",
		description:
			"ReWriter AI is much better, faster, and more efficient than most writers. It is an all-in-one rewriter tool that you can get at a fraction of the price you pay for writers.   All you have to do is to write down your simple sentences in the input box and click “Rewrite”. With multiple options available (standard, creative, formal, etc.) you can create all sorts of content.  That too, at an INSANELY low price.",
	},
	{
		name: "Enhance Productivity.",
		description:
			"No need to drain all your energy over a single article. With ReWriter AI, you can generate much better content in much lesser time.   This means you will have more time to focus on things that are really important. You will have spare time to spend on brand management, lead generation, etc.",
	},
	{
		name: "Unleash YOUR Creativity.",
		description:
			"Unlike other generic ai word rewriter tools, ReWriter AI pro boosts up your content by adding fascinating words and phrases. This means the output generated by RewriterPro.ai will let you know how your content can be amplified.   With each new improvement, you will be able to learn which set of words perfectly describes your business in the most elaborate way possible.",
	},
	{
		name: "Plagiarism-Free Content.",
		description:
			"One of the most important reasons to use ReWriter AI is to generate plagiarism-free content for your brand.   With strict Google policies, it is important to ALWAYS generate content that doesn’t resembles any other published content on the internet.  If you find an interesting paragraph on the internet, copy it and paste it into this spectacular paragraph rewriter to generate the same type of content but in a much better way.",
	},
	{
		name: "Simplify Difficult Content.",
		description:
			"Sometimes, context becomes hard to put into words. That’s why it's unable to get much attention from readers because readers fail to understand its essential meaning.   With ReWriter AI, you will be able to transform your ideas into simple, persuasive, convenient words that will leave an impact on your readers.",
	},
];

export default function Example() {
	return (
		<div className="overflow-hidden bg-gray-100 lg:pb-16">
			<div className="relative mx-auto max-w-xl px-6 lg:max-w-7xl lg:px-8">
				<div className="relative mt-12 lg:mt-6 lg:grid lg:grid-cols-2 lg:items-center lg:gap-8">
					<div className="relative">
						<dl className="mt-10 space-y-10">
							<div key={features1[0].name} className="relative">
								<dt>
									<p className="text-3xl font-bold lg:ml-16 leading-8 text-gray-900 mb-6">
										{features1[0].name}
									</p>
								</dt>
								<dd className="lg:ml-16 mt-2 text-base text-gray-500 blacktext">
									{features1[0].description}
								</dd>
							</div>
						</dl>
					</div>

					<div
						className="relative -mx-0 mt-10 lg:mt-0"
						aria-hidden="true"
					>
						<img
							className="relative mx-auto"
							width={450}
							src={EditorImg1}
							alt=""
						/>
					</div>
				</div>
			</div>
		</div>
	);
}
